services:
  hemrs:
    build: .
    ports:
      - '65534:65534'
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/postgres
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
