[package]
name = "backend"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
axum = { version = "0.7.5", features = ["macros"] }
chrono = { version = "0.4.37", features = ["serde"] }
log = "0.4.21"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
simple_logger = "4.3.3"
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio", "time", "chrono"] }
structopt = "0.3.26"
tokio = { version = "1.37.0", features = ["full"] }
sensors = { path="../sensors"}
