[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
axum = { version = "0.6.20", features = ["macros"] }
chrono = { version = "0.4.31", features = ["serde"] }
log = "0.4.20"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
simple_logger = "4.2.0"
sqlx = { version = "0.7.2", features = ["postgres", "runtime-tokio", "time", "chrono"] }
structopt = "0.3.26"
tokio = { version = "1.34.0", features = ["full"] }
