apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ./docker-compose.yaml convert -o release
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: hemrs
  name: hemrs
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: hemrs
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ./docker-compose.yaml convert -o release
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/hemrs-default: "true"
        io.kompose.service: hemrs
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: env
          image: ghcr.io/frixxie/hemrs:0.11.0 # {"$imagepolicy": "flux-system:hemrs-policy"}
          name: hemrs
          ports:
            - containerPort: 65534
              protocol: TCP
      restartPolicy: Always
