apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ./docker-compose.yaml convert -o release
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: hemrs
  name: hemrs
spec:
  ports:
    - name: "65534"
      port: 65534
      targetPort: 3000
  selector:
    io.kompose.service: hemrs
